# Generated by Django 2.2.5 on 2020-02-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='foodimages')),
                ('cuisine', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('range1', models.CharField(max_length=20)),
                ('range2', models.CharField(max_length=20)),
                ('ingredients', models.CharField(max_length=20000)),
                ('recipe', models.CharField(max_length=20000)),
                ('note', models.CharField(max_length=5000)),
            ],
        ),
    ]
