# Generated by Django 2.2.5 on 2020-03-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_recipe', '0003_auto_20200217_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='foodimages'),
        ),
    ]
