# Generated by Django 2.2.5 on 2020-03-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_recipe', '0004_auto_20200312_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='foodimages/'),
        ),
    ]
