# Generated by Django 2.2.5 on 2020-03-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_recipe', '0005_auto_20200314_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='foodimages'),
        ),
    ]
