# Generated by Django 2.2.5 on 2020-03-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_recipe', '0007_auto_20200314_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default='/media/foodimages/Biryani.jpg', upload_to='foodimages/'),
        ),
    ]
