# Generated by Django 2.2.5 on 2020-03-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_recipe', '0008_auto_20200315_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='foodimages/'),
        ),
    ]
