# Generated by Django 2.2.5 on 2020-03-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200324_1648'),
    ]

    operations = [
    ]
