# Generated by Django 2.2.5 on 2020-03-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200324_1659'),
    ]

    operations = [

    ]
