# Generated by Django 2.2.5 on 2020-03-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
