# Generated by Django 2.2.5 on 2020-03-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cust_id',
            new_name='price',
        ),
    ]
