# Generated by Django 2.2.5 on 2020-03-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ticked',
            field=models.BooleanField(default=False),
        ),
    ]
