# Generated by Django 2.2.5 on 2020-03-24 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200324_1648'),
        ('cart', '0005_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
