# Generated by Django 2.2.5 on 2020-03-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20200324_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='user_id',
            new_name='users',
        ),
    ]
