# Generated by Django 2.2.5 on 2020-03-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20200324_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='users',
        ),
    ]
