# Generated by Django 2.2.5 on 2020-03-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_checkout_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
