# Generated by Django 2.2.5 on 2020-03-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
