# Generated by Django 2.2.5 on 2020-03-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_auto_20200324_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='Amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
