# Generated by Django 2.2.5 on 2020-03-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_checkout_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='Amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='userid',
            field=models.IntegerField(null=True),
        ),
    ]
